### ISSUE TITLE
Comments between postings

### ISSUE THREAD

**Issue by doriath** [jcornaz/beancount_parser_2#29]
I believe the parser is not handling comments between postings in the transactions (the postings after the comment are dropped)

Example:

```
2023-01-01 *
  Assets::A     1 USD
  ; expense
  Expenses:B
```

**Comment by jcornaz** [comment]
Thanks for the report. This is fixed in [1.0.0-alpha.12](https://github.com/jcornaz/beancount_parser_2/releases/tag/v1.0.0-alpha.12)
