### ISSUE TITLE
Support multiple values in options

### ISSUE THREAD

**Issue by doriath** [jcornaz/beancount_parser_2#32]
In my ledger I use following:

```
option "operating_currency" "USD"
option "operating_currency" "CHF"
```

I believe this is supported by fava, to show the sums in those two currencies. In the current parser, HashMap is used with one possible value, which I believe means will drop one of the values. Should `options` hashmap be changed to use `Vec<&str>` as a value?

**Comment by jcornaz** [comment]
Yes, you're right. Currently, it is a bug (or incorrect design). https://beancount.github.io/docs/beancount_language_syntax.html#operating-currencies clearly states (emphasis is mine):

> For this reason, you are able to declare the most common currencies you use in an option:
> `option "operating_currency" "USD"`
> **You may declare more than one.**

We should store the options as `Vec<(&str, &str)>` (or equivalent) and adapt the api.
